name: Download e Upload

on:
  workflow_dispatch:
    inputs:
      app_name:
        description: "Nome do arquivo"
        required: false
      app_link:
        description: "Link do download"
        required: true
      extensao:
        description: "Extensão do arquivo"
        required: true
        type: choice
        options:
          - msixbundle
          - msix
          - appx
          - appxbundle
          - exe
          - msi
          - rspak
          - zip
          - rar
          - 7z

jobs:
  download:
    runs-on: windows-latest
    steps:
      - name: Baixar do link
        run: |
          mkdir files
          curl -L "${{ github.event.inputs.app_link }}" -o ./files/app.${{ github.event.inputs.extensao }}
          
      - name: Upload com Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.app_name && github.event.inputs.app_name || 'meu-app' }}
          path: ./files/
          retention-days: 2
